# Generated by Django 5.0.3 on 2026-09-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("s_no", models.IntegerField(unique=True)),
                ("register_no", models.IntegerField(unique=True)),
                ("status", models.CharField(max_length=1)),
                ("timing", models.DateTimeField(auto_now_add=True)),
                ("stu_photo", models.ImageField(upload_to="student_photo/")),
                ("update_time", models.DateTimeField()),
            ],
        ),
    ]
