# Generated by Django 5.0.3 on 2026-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_remove_student_status_remove_student_update_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="register_no",
            field=models.BigIntegerField(unique=True),
        ),
    ]
