# Generated by Django 5.0.3 on 2026-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_student_register_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stu_attendance",
            name="timing",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="timing",
            field=models.DateField(auto_now_add=True),
        ),
    ]
