# Generated by Django 5.0.3 on 2026-09-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_stu_attendance_timing_alter_student_timing"),
    ]

    operations = [
        migrations.AddField(
            model_name="stu_attendance",
            name="period",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
    ]
