# Generated by Django 5.0.3 on 2026-09-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_stu_attendance_period"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stu_attendance",
            unique_together={("student", "status", "timing", "period")},
        ),
    ]
