# Generated by Django 5.0.3 on 2026-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_stu_attendance_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stu_attendance",
            name="status",
            field=models.CharField(
                choices=[("P", "Present"), ("A", "Absent")], max_length=1
            ),
        ),
    ]
