# Generated by Django 5.0.3 on 2026-09-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_stu_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stu_attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentAttendance",
                to="student.student",
            ),
        ),
    ]
