# Generated by Django 5.0.3 on 2026-09-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_alter_stu_attendance_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stu_attendance",
            name="update_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
