# Generated by Django 5.0.3 on 2026-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_stu_attendance_update_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stu_attendance",
            name="update_time",
            field=models.DateTimeField(),
        ),
    ]
