# Generated by Django 5.0.3 on 2026-09-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_alter_stu_attendance_update_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stu_attendance",
            unique_together={("student", "timing", "period")},
        ),
    ]
